### PR TITLE
rebuild ujson 1.35 for python 3.9

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- manual backport of #23
  - hopefully helps with 
    - https://github.com/conda-forge/ujson-feedstock/issues/12#issuecomment-725365832
    - https://github.com/conda-forge/openpathsampling-feedstock/pull/4

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by dwhswenson** [comment]
Thanks @bollwyvl : FWIW, it looks like this will add a pypy build, as well as 3.9 (the OpenPathSampling update for pypy, https://github.com/conda-forge/openpathsampling-feedstock/pull/6, was previously blocked by a different issue; once that issue was resolved, this one popped up again).

**Comment by bollwyvl** [comment]
Great! Supporting new platforms/architectures is challenging, for sure!

Unfortunately, I'm not a maintainer of this repo, so we'll have to see what @conda-forge/ujson thinks!

**Comment by synapticarbors** [comment]
@bollwyvl -- would you like to be added as a co-maintainer? You can do it in this PR and I'll happily merge it

**Comment by bollwyvl** [comment]
Nah, not looking for more chores, you guys are doing a fine job :muscle:, and no longer have this guy on my critical path anywhere.

**Comment by bollwyvl** [comment]
Hooray! Thanks for the speedy review! I wonder if there is a place to
register long-lived branches that the migrator should consider? Have run
into this in a few places during this transition... Will need osx arm
presumably, too? All hail or robotic overlords!

**Comment by synapticarbors** [comment]
Probably worth raising the issue on gitter or in an issue on https://github.com/conda-forge/conda-forge.github.io/issues

**Pull request merged**
